### PR TITLE
Feature backdrop

### PR DESCRIPTION
**Pull request by alanbosco**
Feature update for the backdrop base on the issue: #231 

1. Prop added 'hideBackdrop' for hiding backdrop.
2. Prop added 'backdropClick' for disabling click to cancel on backdrop (outside click).
3. Updated ReadMe.

### CODE REVIEW

**Comment by mariomka** [comment]
Hi @alanbosco, it seems good! 

I'll try to merge it today later.

**Comment by alanbosco** [comment]
@mariomka Thank you.

**Comment by alanbosco** [comment]
@mariomka Hey, did you get time to merge?

**Comment by mariomka** [comment]
Merged! Thank you. Nice PR, it includes tests and updates in the readme 😍.

I will release a new version in a few minutes.

**Comment by mariomka** [comment]
@alanbosco Published new version `1.0.0-beta.14`

**Pull request merged**
