### PR TITLE
format:macro tokens are supported.

### PR DESCRIPTION
**Pull request by hoythan**
The current format parameters have low extensibility. Add String format to the format parameters without affecting users and allow users to use Macro tokens in Luxon.

### CODE REVIEW

**Comment by larsjanssen6** [comment]
Please accept this!

**Comment by mariomka** [comment]
Thank you, I will review the PR this evening or tomorrow.

**Comment by larsjanssen6** [comment]
@mariomka thanks!

**Comment by IlyaSemenov** [comment]
While we are here, I would actually extend it further and allow passing a custom formatting function to `format` (a simple single argument function which accepts the date/time value and returns formatted string inputValue).

I just stumbled upon a situation where I need to format the value in two different timezones (server and user local). I ended up adding a separate div alongside the date picker input, but it would be great if I could just format the whole string myself.

**Comment by hoythan** [comment]
**waiting**

**Comment by mariomka** [comment]
Finally merged, Sorry I do not have much time.

**Pull request merged**
