### PR TITLE
Removed selection highlighting of text

### PR DESCRIPTION
**Pull request by chrfs**

### CODE REVIEW

**Comment by mariomka** [comment]
I don't know if it is useful or not.
Why do you want to remove selection?

**Comment by chrfs** [comment]
Thanks for your quick response. For instance, if I click several times through the months I get this:
screenshot 2019-01-20 at 10 47 03

**Comment by chrfs** [comment]
This is still an issue..

**Comment by mariomka** [comment]
I'm sorry, but this PR is for the old unmaintained version 0.x.

**Pull request closed without merging**
