### PR TITLE
add localize for picker buttons, update example in docs

### PR DESCRIPTION
**Pull request by masquel**
Added new propeprty called `buttonTexts` to improve UI by localizing buttons with calendar

### CODE REVIEW

**Comment by mariomka** [comment]
I'm sorry, last week I was busy.

Please, can you revert build files? I generate it on each release.

Furthermore, I think that property name can be more generally for future new strings, something like `language` or similar.

**Comment by masquel** [comment]
@mariomka here it is. You should add dev build config :)

**Comment by mariomka** [comment]
Merged, thank you.

**Comment by mariomka** [comment]
Version 0.5.3 adds `language` param, but new version 0.6.0 replace `location` by `moment-location` and `language` by `i18n` to be more comprenssive.

**Pull request merged**
