### PR TITLE
input cleaning button added.

### PR DESCRIPTION
**Pull request by ghost**
Hi, I needed to clear the button. I figured it out with a little method. I wanted to share it with the community as well.

### CODE REVIEW

**Comment by 8alery** [comment]
Having a clear feature would be very nice! I hope this functionality will be added to main branch.

**Comment by wishinghand** [comment]
Would love this feature too. Just ran into a case where clearable dates are needed.

**Comment by mariomka** [comment]
I'm going to close this PR. Right now You can add a reset button from outside of the component. Also, add a span element would break some customizations.

**Comment by wishinghand** [comment]
That's a shame. Perhaps include the code to do this in the docs so it'd be easy for those who need it to look it up?

**Pull request closed without merging**
