### PR TITLE
Readme - register component when using CDN

### PR DESCRIPTION
**Pull request by LukaszWiktor**
Adding a code snippet to README.md showing how to register the component when using the approach with CDN. 
Took me a while to figure it out.

### CODE REVIEW

**Comment by mariomka** [comment]
The browser file should register the components.

Can you try this snippet?

```html
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" href="https://unpkg.com/vue-datetime@1.0.0-beta.11/dist/vue-datetime.css"></link>
</head>

<body>
<div id="app">
  <datetime type="datetime" v-model="datetime"></datetime>

  <pre><code>{{ datetime }}</code></pre>
</div>

<script src="https://unpkg.com/vue@2.6.11/dist/vue.min.js"></script>
<script src="https://moment.github.io/luxon/global/luxon.js"></script>
<script src="https://unpkg.com/weekstart@1.0.1/dist/min/main.js"></script>
<script src="https://unpkg.com/vue-datetime@1.0.0-beta.11/dist/vue-datetime.js"></script>

<script>
var vm = new Vue({
  el: '#app',
  data () {
    return {
      datetime: '2013-01-10T23:02:28.037Z'
    }
  }
});
</script>
</body>
</html>

```

**Comment by LukaszWiktor** [comment]
Thanks @mariomka, it works! I was not aware that vue-datetime registers itself. Actually, there was a moment when I tried `<vue-datetime>`, but it didn't work. I can see now that the component registers itself under `<datetime>`. This is indeed consistent with other code snippets, but it wasn't obvious to me. Maybe it would be worth adding a note about it?

**Comment by mariomka** [comment]
Definitely yes, I think it is worth it.

**Comment by LukaszWiktor** [comment]
I added a note about auto-registration. I also left the code snippet in case someone wanted to register the component under a custom name.

**Comment by mariomka** [comment]
Thank you

**Pull request merged**
