### PR TITLE
Added new custom slots for Buttons

### PR DESCRIPTION
**Pull request by bartrail**
I needed to add some FontAwesome Icons to the Confirm/Cancel Buttons so I added 2 new slots for it. Hope all is done well. Tests should pass.
Cheers

### CODE REVIEW

**Comment by jasonlfunk** [comment]
If we add `slot-scope`s to the slots, then I can do this:

```
<template slot="button-confirm" slot-scope="scope">
    <span v-if='scope.step === "date"'>Next <i class='fas fa-arrow-right' /></span>
    <span v-else><i class='fas fa-check-circle' /> Publish</span>
</template>
```

publish

**Comment by bartrail** [comment]
Great idea! I just updated my PR accordingly

**Review by y4roc — APPROVED** [review]

**Comment by mariomka** [comment]
It sounds well. I will check soon, I am a bit busy.

**Comment by bartrail** [comment]
did you find some time to check the pull request?

**Review by WoodrowShigeru — APPROVED** [review]

**Comment by mariomka** [comment]
I'm sorry for the delay. It will be available in next version planned for today later.

**Pull request merged**
