### PR TITLE
Add 12/24 hour format option to the TimePicker.

### PR DESCRIPTION
**Pull request by jasonlfunk**
This PR adds a 12/24 hour format to the time picker.

### CODE REVIEW

**Comment by mariomka** [comment]
Thank you for the contribution. I need some time to review but seem to be a good feature.

**Comment by jasonlfunk** [comment]
Sounds good. If you have any questions, let me know.

**Comment by mariomka** [comment]
I'll merge it now. I have changed the property name and type, added some tests and fixed auto close.

**Comment by jasonlfunk** [comment]
Thanks for merging this. When do you expect to publish the next beta version that includes these changes?

**Pull request merged**
